name: Daily NDVI Export

on:
  schedule:
    - cron: "0 18 * * *"   # 6am NZ time
  workflow_dispatch:

jobs:
  run-ndvi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run NDVI export
        env:
          EE_KEY: ${{ secrets.EE_KEY }}
        run: python export_ndvi.py
